### ISSUE TITLE
Error loading binder instance

### ISSUE THREAD

**Issue by liamtoney** [liamtoney/ashfall_visual#19]
With the new `environment.yml`, the build logs give the error
```
Removing intermediate container ed4f233efc4b
unknown parent image ID sha256:097df48afdf2914096121aa3424e36c87abf33e5caa832145405ec068fe96966
```

**Comment by liamtoney** [comment]
Reverting to the [previously-functional `environment.yml`](https://github.com/liamtoney/ashfall_visual/blob/ab3f76925a26fb04e988b4f4d49a1e0a6829c6e8/environment.yml) gives the above error as well. This is confusing...

**Comment by liamtoney** [comment]
@yannikbehr have you ever encountered this issue before?

**Comment by yannikbehr** [comment]
Nope, sorry. I have zero experience with binder except from what I've seen you doing with it. It looks like a docker issue but I can't remember coming across it before.

**Comment by liamtoney** [comment]
Update: I tried running it a few more times and on the 3rd or 4th try it successfully built. Something funky is going on. Seems unrelated to the setup of the `environment.yml` file (contrary to what I initially thought). Anyhow, it works for now!

 `¯\_(ツ)_/¯`

**Comment by yannikbehr** [comment]
sweet as
